[dependencies]
facet = {path = "../facet/facet"}
facet-json = {path = "../facet/facet-json/"}
facet-reflect = {path = "../facet/facet-reflect/"}

[package]
name = "facet-validate"
version = "0.1.0"
edition = "2024"
