[package]
name = "facet-validate"
version = "0.1.0"
edition = "2024"

[dependencies]
facet = { git = "https://github.com/facet-rs/facet.git", version = "0.2.0" }
facet-json = { git = "https://github.com/facet-rs/facet.git", version = "0.2.2" }
facet-reflect = { git = "https://github.com/facet-rs/facet.git", version = "0.6.2" }
